"""
ClawMate shared constants — imported by routes.py, service.py, feedback_api.py.
"""

# Config env var names
PUBLIC_BASE_URL_ENV = "CLAWMATE_PUBLIC_BASE_URL"
CONFIG_PATH_ENV = "CLAWMATE_CONFIG"
ONLYOFFICE_JWT_SECRET_ENV = "CLAWMATE_ONLYOFFICE_JWT_SECRET"
PREVIEW_TOKEN_SECRET_ENV = "CLAWMATE_PREVIEW_TOKEN_SECRET"
ONLYOFFICE_URL_ENV = "CLAWMATE_ONLYOFFICE_URL"
